### ISSUE TITLE
Let's Wrap Up Wrapped 2023

### ISSUE THREAD

**Issue by YodaLightsabr** [hackclub/hcb-wrapped-2023#1]
```[tasklist]
### Slides
- [ ] https://github.com/hackclub/hcb-wrapped-2023/issues/3
- [ ] https://github.com/hackclub/hcb-wrapped-2023/issues/4
- [ ] https://github.com/hackclub/hcb-wrapped-2023/issues/5
- [ ] https://github.com/hackclub/hcb-wrapped-2023/issues/6
- [ ] https://github.com/hackclub/hcb-wrapped-2023/issues/8
- [ ] https://github.com/hackclub/hcb-wrapped-2023/issues/13
- [ ] https://github.com/hackclub/hcb-wrapped-2023/issues/12
- [ ] https://github.com/hackclub/hcb-wrapped-2023/issues/11
- [ ] https://github.com/hackclub/hcb-wrapped-2023/issues/10
- [ ] https://github.com/hackclub/hcb-wrapped-2023/issues/9
- [ ] And more!
```
